# Deploy to these servers.
servers:
  - 134.122.34.75

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    RAILS_ENV: staging
    MAILER_SENDER: hello@teloslabs.co
    LITESTREAM_BACKUP_ENABLED: true
    SESSION_REMINDERS_ENABLED: true
  secret:
    - APP_HOST
    - RAILS_MASTER_KEY
    - MAILPACE_API_TOKEN
    - APPSIGNAL_PUSH_API_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - LITESTREAM_BUCKET
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY

accessories:
  vector:
    image: timberio/vector:0.39.0-debian
    roles:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    files:
      - "./config/vector/vector_staging.yaml:/etc/vector/vector.yaml"
